### ISSUE TITLE
Remove dependency to mainflux

### ISSUE THREAD

**Issue by JulienTant** [mainflux/mproxy#26]
Hello,

Thank you for providing such a nice project!

I wanted to use mproxy within my own project but got into problems because of mproxy dependency to mainflux: my project need a specific version of GoCQL and it's a different one that mainflux is requiring. 

Would you accept a PR that:
1- Copy the interface from Mainflux here to remove that dependeny.
2- Use simple go errors instead of mainflux pkg/errors ?

Thanks for your time & consideration.

**Comment by drasko** [comment]
Huh :)

I did not understand 1) - this copy of interface from Mainflux. Which interface?

For 2 - mProxy is tightly related to Mainflux and used in MQTT adapter of Mainflux. In case you remove `pkg/errors` from here, we will be adding extra dependencies in Mainflux (because it uses mProxy).

Wouldn't it make more sense to update Mainflux GoCQL version if needed? What is wrong with the current version - it needs to be bumped up I hope (please don't tell me that we need to downgrade :)).

**Comment by drasko** [comment]
Take care also that we use Mainflux logger... Just to clarify - do you need to remove all Mainflux dependencies, to just fix your GoCQL problem?

**Comment by drasko** [comment]
@dusanb94 @nmarcetic opinions?

**Comment by dusanb94** [comment]
I'm also not sure that I understand what's the issue here. Maybe this PR would make sense, but, please, don't do anything before we understand the problem. Mainflux dependencies are quite generic, we depend only on `logger` and `errors` packages that are fairly simple and should not cause any compatibility issues.

**Comment by JulienTant** [comment]
Hi,

Thanks for your time, and sorry if my message was not clear enough I'll try to be more precise.

I understand that mProxy is a dependency of Mainflux, and in that case Mainflux is also a dependency of mProxy (because the Logger interface is imported from there. and because of the usage of the errors package). My issue is that polling mProxy in my project also force me to poll Mainflux, and `go mod` while doing its job of dependency resolution try to merge versions. 

I have to use old versions of gocql in that project (yeah, it's annoying ^^), but because Mainflux is using a more recent version, `go mod` will try to enforce that newer version. I have a workaround if I need it, i can add int my `go.mod` file something like:

```
replace 	github.com/gocql/gocql =>  github.com/gocql/gocql v0.0.0-20180617115710-e06f8c1bcd78
```

But that's a workaround more than a solution ^^ My idea was to help making mProxy more "standalone" as a lib by removing hard dependecies to Mainflux by:

 1- Copy the interface from Mainflux here to remove that dependency. By doing that, the package is responsible for declaring the interfaces it required to work. This is what's used in most packages on the market.
2- I was offering to use regular "go errors" instead of `github.com/mainflux/mainflux/pkg/errors`.  I know this lib helps wrapping errors & all which is pretty cool, but it forces anyone who would like to use mProxy to download Mainflux (as `github.com/mainflux/mainflux/pkg/errors` itself is not declared as a module but just of package of mainflux)

Anyway those are changes that I'll have to do to be able to use mProxy more easily, and the license Apache 2 imply that I have to let you know. If you think those changes makes sense, I'll be happy to offer a PR.
